force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Billing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Billing</relationshipLabel>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/Contact_Quote_Junction__c.object-meta.xml
<CustomObject>
    <label>Contact Quote Junction</label>
    <nameField>
        <displayFormat>CQJ-{000000000}</displayFormat>
        <label>Contact Quote Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Quote Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote_Relationships</relationshipLabel>
    <relationshipName>Quote_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Contact Quote Junctions</relationshipLabel>
    <relationshipName>Contact_Quote_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q{000000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConfirmationControllerTest.cls
@IsTest
public with sharing class ConfirmationControllerTest {
    public ConfirmationControllerTest() {}

    @TestSetup
    static void makeData(){
        Quote__c q = new Quote__c();
        insert q;
        Contact c1 = new Contact();
        c1.LastName = 'Test User 1';
        insert c1;
        Contact_Quote_Junction__c cq1 = new Contact_Quote_Junction__c();
        cq1.Contact__c = c1.Id;
        cq1.Quote__c = q.Id;
        insert cq1;
        Contact c2 = new Contact();
        c2.LastName = 'Test User 2';
        insert c2;
        Contact_Quote_Junction__c cq2 = new Contact_Quote_Junction__c();
        cq2.Contact__c = c2.Id;
        cq2.Quote__c = q.Id;
        insert cq2;
        Vehicle__c v = new Vehicle__c();
        v.Quote__c = q.Id;
        insert v;
        Billing__c b = new Billing__c();
        b.Quote__c = q.Id;
        insert b;
    }

    static testmethod void testControllerQuery(){
        
        Test.startTest();
       
        List<Quote__c> quotes = [SELECT Id from Quote__c];
        ConfirmationController.queryAllQuoteDetails(quotes[0].Id);
    
        Test.stopTest();
        
    }


}