force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Billing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Paperless_Billing__c.field-meta.xml
<CustomField>
    <fullName>Paperless_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paperless Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Paperless_Policy__c.field-meta.xml
<CustomField>
    <fullName>Paperless_Policy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paperless Policy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Pay_Plan__c.field-meta.xml
<CustomField>
    <fullName>Pay_Plan__c</fullName>
    <label>Pay Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Banking Payments</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Billing</relationshipLabel>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/Contact_Quote_Junction__c.object-meta.xml
<CustomObject>
    <label>Contact Quote Junction</label>
    <nameField>
        <displayFormat>CQJ-{000000000}</displayFormat>
        <label>Contact Quote Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Quote Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote_Relationships</relationshipLabel>
    <relationshipName>Quote_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Contact Quote Junctions</relationshipLabel>
    <relationshipName>Contact_Quote_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Policy Holder</fullName>
            </value>
            <value>
                <fullName>Additional Policy Holder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q{000000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bodily Injury</fullName>
            </value>
            <value>
                <fullName>Property Damage</fullName>
            </value>
            <value>
                <fullName>Underinsured Motorist</fullName>
            </value>
            <value>
                <fullName>Uninsured Motorist</fullName>
            </value>
            <value>
                <fullName>Death &amp; Disbursement</fullName>
            </value>
            <value>
                <fullName>Income Disability</fullName>
            </value>
            <value>
                <fullName>Medical and Hospital Benefits</fullName>
            </value>
            <value>
                <fullName>Comprehension</fullName>
            </value>
            <value>
                <fullName>Collision</fullName>
            </value>
            <value>
                <fullName>Glass deductible buybacks</fullName>
            </value>
            <value>
                <fullName>Towing and Road Service</fullName>
            </value>
            <value>
                <fullName>Collision Plus/loss</fullName>
            </value>
            <value>
                <fullName>Rental Reimbursement Coverage</fullName>
            </value>
            <value>
                <fullName>Residual Debt Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Coverage_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Start_Date__c</fullName>
    <label>Coverage Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Total__c.field-meta.xml
<CustomField>
    <fullName>Quote_Total__c</fullName>
    <label>Quote Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Annual_Distance__c.field-meta.xml
<CustomField>
    <fullName>Annual_Distance__c</fullName>
    <label>Annual Distance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Under 5,000 miles</fullName>
            </value>
            <value>
                <fullName>5,001 - 10,000 miles</fullName>
            </value>
            <value>
                <fullName>10,001 - 20,000 miles</fullName>
            </value>
            <value>
                <fullName>20,000+ miles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Business_Use__c.field-meta.xml
<CustomField>
    <fullName>Business_Use__c</fullName>
    <label>Business Use</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bodily Injury</fullName>
            </value>
            <value>
                <fullName>Property Damage</fullName>
            </value>
            <value>
                <fullName>Underinsured Motorist</fullName>
            </value>
            <value>
                <fullName>Uninsured Motorist</fullName>
            </value>
            <value>
                <fullName>Death &amp; Disbursement</fullName>
            </value>
            <value>
                <fullName>Income Disability</fullName>
            </value>
            <value>
                <fullName>Medical and Hospital Benefits</fullName>
            </value>
            <value>
                <fullName>Comprehension</fullName>
            </value>
            <value>
                <fullName>Collision</fullName>
            </value>
            <value>
                <fullName>Glass deductible buybacks</fullName>
            </value>
            <value>
                <fullName>Towing and Road Service</fullName>
            </value>
            <value>
                <fullName>Collision Plus/loss</fullName>
            </value>
            <value>
                <fullName>Rental Reimbursement Coverage</fullName>
            </value>
            <value>
                <fullName>Residual Debt Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Daily_Commute__c.field-meta.xml
<CustomField>
    <fullName>Daily_Commute__c</fullName>
    <label>Daily Commute (miles)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Prior_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Prior_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prior Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Purchase_Condition__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Condition__c</fullName>
    <label>Purchase Condition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <label>VIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfirmationController.cls
public with sharing class ConfirmationController {
    public ConfirmationController() {

    }

    public static Quote__c queryAllQuoteDetails(String quoteId) {
        Quote__c quote = [SELECT Coverage_Start_Date__c,Coverage__c,Description__c,Discount__c,Expiration_Date__c,Id,Name,OwnerId,Quote_Total__c,Status__c,Subtotal__c,Tax__c,
                          (SELECT Annual_Distance__c,Business_Use__c,Daily_Commute__c,Id,Make__c,Model__c,Name,OwnerId,Prior_Coverage__c,Purchase_Condition__c,Quote__c,VIN__c,Year__c 
                           FROM Vehicles__r),
                          (SELECT Bank_Account_Number__c,Bank_Name__c,Bank_Transit_Number__c,Billing_City__c,Billing_Country__c,Billing_Email__c,Billing_Postal_Code__c,Billing_State__c,
                                  Billing_Street__c,CC_Expiry_Month__c,CC_Expiry_Year__c,CC_Security_Code__c,CreatedById,CreatedDate,Credit_Card_Number__c,Due_Date__c,Id,Name,OwnerId,
                                  Paperless_Billing__c,Paperless_Policy__c,Payment_Method__c,Payment_Name__c,Pay_Plan__c,Quote__c
                           FROM Billing__r),
                           (SELECT Id, Name, Role__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.MailingCity,Contact__r.MailingCountry,Contact__r.MailingLatitude,
                           Contact__r.MailingLongitude,Contact__r.MailingPostalCode,Contact__r.MailingState,Contact__r.MailingStreet  FROM Contact_Quote_Junctions__r)
                          FROM Quote__c 
                          WHERE Id = :quoteId 
                          LIMIT 1];
        return quote;
    }
}