force-app/main/default/objects/Annuity__c/Annuity__c.object-meta.xml
<CustomObject>
    <label>Annuity</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Annuity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annuities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annuity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Annuities</relationshipLabel>
    <relationshipName>Annuities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Billing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Billing</relationshipLabel>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/Contact_Quote_Junction__c.object-meta.xml
<CustomObject>
    <label>Contact Quote Junction</label>
    <nameField>
        <displayFormat>CQJ-{000000000}</displayFormat>
        <label>Contact Quote Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Quote Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote_Relationships</relationshipLabel>
    <relationshipName>Quote_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Contact Quote Junctions</relationshipLabel>
    <relationshipName>Contact_Quote_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Quote_Junction__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Policy Holder</fullName>
            </value>
            <value>
                <fullName>Additional Policy Holder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Life__c/Life__c.object-meta.xml
<CustomObject>
    <label>Life</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Life ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Life__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Lives</relationshipLabel>
    <relationshipName>Lives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Property ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q{000000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteConfirmationDetails.cls
public class QuoteConfirmationDetails {
    @AuraEnabled
    public static Quote__c getAllQuoteInfo(String quoteId) {

		Quote__c output = [SELECT Id,
             (SELECT Id FROM Vehicles__r),
             (SELECT Id FROM Properties__r),
             (SELECT Id FROM Lives__r),
             (SELECT Id FROM Annuities__r),
             (SELECT Id FROM Billing__r),
             (SELECT Role__c, Contact__r.Id FROM Contact_Quote_Junctions__r)
        FROM Quote__c WHERE Id = :quoteId LIMIT 1];
        
        return output;
    }
}