force-app/main/default/objects/Annuity__c/Annuity__c.object-meta.xml
<CustomObject>
    <label>Annuity</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Annuity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annuities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annuity__c/fields/Monthly_Income_10_Year__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Income_10_Year__c</fullName>
    <label>Monthly Income 10 Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annuity__c/fields/Monthly_Income_20_Year__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Income_20_Year__c</fullName>
    <label>Monthly Income 20 Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annuity__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Annuities</relationshipLabel>
    <relationshipName>Annuities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Life__c/Life__c.object-meta.xml
<CustomObject>
    <label>Life</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Life ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Life__c/fields/Employed__c.field-meta.xml
<CustomField>
    <fullName>Employed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Life__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Lives</relationshipLabel>
    <relationshipName>Lives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Life__c/fields/Tobacco_Usage__c.field-meta.xml
<CustomField>
    <fullName>Tobacco_Usage__c</fullName>
    <label>Tobacco Usage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Never</fullName>
            </value>
            <value>
                <fullName>None in the last 5 years</fullName>
            </value>
            <value>
                <fullName>None in the last 4 years</fullName>
            </value>
            <value>
                <fullName>None in the last 3 years</fullName>
            </value>
            <value>
                <fullName>None in the last 2 years</fullName>
            </value>
            <value>
                <fullName>None in the last 1 years</fullName>
            </value>
            <value>
                <fullName>Last 12 months, less than 24 per year</fullName>
            </value>
            <value>
                <fullName>Last 12 months, more than 24 per year</fullName>
            </value>
            <value>
                <fullName>Last 12 months, nicotine replacement (gum, patch, etc)</fullName>
            </value>
            <value>
                <fullName>Last 12 months, cigar use, 12 or less per year</fullName>
            </value>
            <value>
                <fullName>Last 12 months, cigar use, 12 or more per year</fullName>
            </value>
            <value>
                <fullName>Last 12 months, chewing tobacco, pipe or snuff</fullName>
            </value>
            <value>
                <fullName>Last 12 months, marjiuana use, 2 or less per month</fullName>
            </value>
            <value>
                <fullName>Last 12 months, marjiuana use, 2 or more per month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Property ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Belongings</fullName>
            </value>
            <value>
                <fullName>Extra Expenses</fullName>
            </value>
            <value>
                <fullName>Personal Liability</fullName>
            </value>
            <value>
                <fullName>Policy Deductible</fullName>
            </value>
            <value>
                <fullName>Sewer Backup</fullName>
            </value>
            <value>
                <fullName>Overland Water</fullName>
            </value>
            <value>
                <fullName>Full Hail</fullName>
            </value>
            <value>
                <fullName>Earthquake</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q{000000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bodily Injury</fullName>
            </value>
            <value>
                <fullName>Property Damage</fullName>
            </value>
            <value>
                <fullName>Underinsured Motorist</fullName>
            </value>
            <value>
                <fullName>Uninsured Motorist</fullName>
            </value>
            <value>
                <fullName>Death &amp; Disbursement</fullName>
            </value>
            <value>
                <fullName>Income Disability</fullName>
            </value>
            <value>
                <fullName>Medical and Hospital Benefits</fullName>
            </value>
            <value>
                <fullName>Comprehension</fullName>
            </value>
            <value>
                <fullName>Collision</fullName>
            </value>
            <value>
                <fullName>Glass deductible buybacks</fullName>
            </value>
            <value>
                <fullName>Towing and Road Service</fullName>
            </value>
            <value>
                <fullName>Collision Plus/loss</fullName>
            </value>
            <value>
                <fullName>Rental Reimbursement Coverage</fullName>
            </value>
            <value>
                <fullName>Residual Debt Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_General__c/Rule_General__c.object-meta.xml
<CustomObject>
    <label>Rule General</label>
    <nameField>
        <displayFormat>RG-{000000000}</displayFormat>
        <label>Rule General ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules General</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_General__c/fields/Adjustment_Percent__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Percent__c</fullName>
    <label>Adjustment Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Rule_General__c/fields/Fixed_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Adjustment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fixed Adjustment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rule_General__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <label>Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bodily Injury</fullName>
            </value>
            <value>
                <fullName>Property Damage</fullName>
            </value>
            <value>
                <fullName>Underinsured Motorist</fullName>
            </value>
            <value>
                <fullName>Uninsured Motorist</fullName>
            </value>
            <value>
                <fullName>Death &amp; Disbursement</fullName>
            </value>
            <value>
                <fullName>Income Disability</fullName>
            </value>
            <value>
                <fullName>Medical and Hospital Benefits</fullName>
            </value>
            <value>
                <fullName>Comprehension</fullName>
            </value>
            <value>
                <fullName>Collision</fullName>
            </value>
            <value>
                <fullName>Glass deductible buybacks</fullName>
            </value>
            <value>
                <fullName>Towing and Road Service</fullName>
            </value>
            <value>
                <fullName>Collision Plus/loss</fullName>
            </value>
            <value>
                <fullName>Rental Reimbursement Coverage</fullName>
            </value>
            <value>
                <fullName>Residual Debt Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteCalculations.cls
public class QuoteCalculations {
    static final decimal vehicle_base = 100.0;
    static final decimal home_base = 1000.0;
    static final decimal life_pct = 100.0;
    static final decimal annuity_pct = 100.0;
    static final decimal tax_percent = 0.1;
    
    @InvocableMethod
    public static List<Quote__c> setQuotePrice(List<String> quoteId) {
        decimal subtotal = 0.0;
        
		List<Quote__c> quotes = [SELECT Id, Discount__c, Start_Date__c, Expiry_Date__c, 
                          		 Status__c, Subtotal__c, Tax__c, Total__c from Quote__c WHERE Id IN :quoteId];
        
        List<Rule_General__c> vehicle_rules = [SELECT Id, Rule_Type__c, Fixed_Adjustment__c, Name__c, Adjustment_Percent__c, 
                                      		   Adjustment_Amount__c FROM Rule_General__c WHERE Rule_Type__c = 'Auto'];
        
        List<Rule_General__c> home_rules = [SELECT Id, Rule_Type__c, Fixed_Adjustment__c, Name__c, Adjustment_Percent__c, 
                                      		Adjustment_Amount__c FROM Rule_General__c WHERE Rule_Type__c = 'Home'];
        
        List<Rule_General__c> both_rules = [SELECT Id, Rule_Type__c, Fixed_Adjustment__c, Name__c, Adjustment_Percent__c, 
                                            Adjustment_Amount__c FROM Rule_General__c WHERE Rule_Type__c = 'Both'];
        decimal combo_discount = 1 + both_rules[0].Adjustment_Percent__c / 100;
                
        List<Integer> output = new Integer[quotes.size()];
        
        for (Quote__c q : quotes) {
            List<Vehicle__c> vehicles = [SELECT Id, Quote__c, Coverage__c FROM Vehicle__c WHERE Quote__c = :q.Id];
            for (Vehicle__c v : vehicles) {
                decimal vehicleCost = vehicle_base;
                String coverageRaw = v.Coverage__c;
                
	            if (String.isNotBlank(coverageRaw) ) {
                    String[] coverages = coverageRaw.split(';');
                    
                    for (String c : coverages) {
                        for (Rule_General__c rule : vehicle_rules) {
                            if (c == rule.Name__c) {
                                if (rule.Fixed_Adjustment__c) {
                                    vehicleCost += rule.Adjustment_Amount__c;
                                }
                                else {
                                    vehicleCost = vehicleCost * (1 + rule.Adjustment_Percent__c / 100);
                                }
                                
                                break;
                            }
                        }
                    }                                
                }
                
                subtotal += vehicleCost;
            }
            
            List<Property__c> properties = [SELECT Id, Quote__c, Coverage__c FROM Property__c WHERE Quote__c = :q.Id];
			for (Property__c p : properties) {
                decimal propertyCost = home_base;
                String coverageRaw = p.Coverage__c;
                
                if (String.isNotBlank(coverageRaw)) {
                    String[] coverages = coverageRaw.split(';');
                    
                    for (String c : coverages) {
                        for (Rule_General__c rule : home_rules) {
                            if (c == rule.Name__c) {
                                if (rule.Fixed_Adjustment__c) {
                                    propertyCost += rule.Adjustment_Amount__c;
                                }
                                else {
                                    propertyCost = propertyCost * (1 + rule.Adjustment_Percent__c / 100);
                                }
                                    
                                break;
                            }
                        }
                    }
                }
                    
                subtotal += propertyCost;
            }
            
            if (vehicles.size() > 0 && properties.size() > 0) {
                subtotal = subtotal * combo_discount;
            }

			/*********** Life & Annuity Calculations Start ***********/

            List<Annuity__c> annuities = [SELECT Id, Quote__c, Amount__c, Monthly_Income__c, Monthly_Income_10_Year__c, 
                                          Monthly_Income_20_Year__c FROM Annuity__c WHERE Quote__c = :q.Id];
			for (Annuity__c a : annuities) {
                decimal annuityCost = a.Amount__c;
                
                a.Monthly_Income__c = a.Amount__c * 0.02 / 12;
                a.Monthly_Income_10_Year__c = a.Amount__c / 10 / 12 * 2;
                a.Monthly_Income_20_Year__c = a.Amount__c / 20 / 12 * 2;
                subtotal += a.Amount__c * 0.9;
            }

            List<Life__c> lives = [SELECT Id, Quote__c, Amount__c, Height__c, Weight__c, Tobacco_Usage__c, Employed__c,
                                   Bankruptcy__c FROM Life__c WHERE Quote__c = :q.Id];
			for (Life__c l : lives) {
                decimal lifeCost = l.Amount__c / 30 / 12 / 2;
                lifeCost = (l.Tobacco_Usage__c == 'Never') ? lifeCost : lifeCost * 1.2;
                lifeCost = l.Employed__c ? lifeCost : lifeCost * 1.1;
                lifeCost = l.Bankruptcy__c ? lifeCost : lifeCost * 1.3;
                
                subtotal += lifeCost;
            }
            
			/************ Life & Annuity Calculations End ************/
            
            q.Subtotal__c = subtotal;
            q.Tax__c = subtotal * tax_percent;
            q.Total__c = subtotal * (1+tax_percent);
            q.Start_Date__c = date.today();
            // q.Expiry_Date__c = q.Start_Date__c.addYears(3);
        }
        
        update quotes; 
        
        return quotes;
    }
}